apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: service-discovery-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: service-discovery
    spec:
      containers:
      - name: alpine-kubectl-etcd
        image: rlxs/alpine-s:latest